version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hirequick_postgres_local
    environment:
      POSTGRES_USER: hirequickUser 
      POSTGRES_PASSWORD: hirequickPassword
      POSTGRES_DB: hirequick_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hirequickUser -d hirequick_database"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
