# HireQuick Application Configuration
spring.application.name=HireQuick

# Server port
server.port=8080

# profile for the application
spring.profiles.active=dev

# Configuration for the Documentation Generation
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# context-path for the application
server.servlet.context-path=/api/v1

