# HireQuick Application Configuration
spring.application.name=HireQuick

# Server port
server.port=8080

# profile for the application
spring.profiles.active=dev

# context-path for the application
server.servlet.context-path=/api/v1

