# Profil
spring.profiles.active=dev

# Hibernate gère automatiquement le schéma
spring.jpa.hibernate.ddl-auto=update

# Base de données locale
spring.datasource.url=jdbc:postgresql://localhost:5432/hirequick_db
spring.datasource.username=hirequick
spring.datasource.password=hirequick123
spring.datasource.driver-class-name=org.postgresql.Driver
