# Base de données locale
spring.datasource.url=jdbc:postgresql://localhost:5432/hirequick_database
spring.datasource.username=hirequickUser
spring.datasource.password=hirequickPassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate : création automatique des tables au démarrage et suppression à l'arrêt
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

