# Nom de l'application
spring.application.name=HireQuick

# Port du serveur
server.port=8080

# Contexte API
server.servlet.context-path=/api/v1

# JPA / Hibernate configuration commune
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Flyway activé partout
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
