# Profil
spring.profiles.active=prod

# Hibernate vérifie uniquement le schéma (pas de création/modification auto)
spring.jpa.hibernate.ddl-auto=validate

# Base de données Neon (prod)
spring.datasource.url=jdbc:postgresql://ep-cool-name-123456.us-east-2.aws.neon.tech:5432/hirequick_db
spring.datasource.username=alex
spring.datasource.password=AbCdEfGhIjKlMnOp
spring.datasource.driver-class-name=org.postgresql.Driver
